---
all:
  children:
    spines:
      hosts:
        spine1:
          ansible_host: 10.0.0.60
        spine2:
          ansible_host: 10.0.0.60
    routers:
      hosts:
        csr1:
          ansible_host: 10.0.0.50
        csr2:
          ansible_host: 10.0.0.50
    eos:
      children:
        spines:
    ios:
      children:
        routers:
      



